/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kalkulator;

/**
 *
 * @author Fareladzin Wibi
 */
public class Standard extends javax.swing.JFrame {
    String bil="";
    double jumlah,bil1,bil2;
    int pilih;

    /**
     * Creates new form Standard
     */
    public Standard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_hasil = new javax.swing.JTextArea();
        bt_7 = new javax.swing.JButton();
        bt_4 = new javax.swing.JButton();
        bt_8 = new javax.swing.JButton();
        bt_5 = new javax.swing.JButton();
        bt_9 = new javax.swing.JButton();
        bt_6 = new javax.swing.JButton();
        bt_1 = new javax.swing.JButton();
        bt_C = new javax.swing.JButton();
        bt_2 = new javax.swing.JButton();
        bt_titik = new javax.swing.JButton();
        bt_3 = new javax.swing.JButton();
        bt_hasil = new javax.swing.JButton();
        bt_tambah = new javax.swing.JButton();
        bt_kurang = new javax.swing.JButton();
        bt_kali = new javax.swing.JButton();
        bt_bagi = new javax.swing.JButton();
        bt_mod = new javax.swing.JButton();
        bt_10 = new javax.swing.JButton();
        bt_sisabagi1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator Sederhana");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(198, 173, 149));
        jPanel1.setToolTipText("KalkulatorSederhana");
        jPanel1.setName("Kalkulator Sederhana"); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel1.setText(" Kalkulator Standard");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 20, 280, 50);

        txt_hasil.setEditable(false);
        txt_hasil.setColumns(20);
        txt_hasil.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txt_hasil.setRows(5);
        jScrollPane1.setViewportView(txt_hasil);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 70, 310, 90);

        bt_7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_7.setText("7");
        bt_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_7ActionPerformed(evt);
            }
        });
        jPanel1.add(bt_7);
        bt_7.setBounds(40, 180, 60, 50);

        bt_4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_4.setText("4");
        bt_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_4ActionPerformed(evt);
            }
        });
        jPanel1.add(bt_4);
        bt_4.setBounds(40, 240, 60, 50);

        bt_8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_8.setText("8");
        bt_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_8ActionPerformed(evt);
            }
        });
        jPanel1.add(bt_8);
        bt_8.setBounds(110, 180, 60, 50);

        bt_5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_5.setText("5");
        bt_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_5ActionPerformed(evt);
            }
        });
        jPanel1.add(bt_5);
        bt_5.setBounds(110, 240, 60, 50);

        bt_9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_9.setText("9");
        bt_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_9ActionPerformed(evt);
            }
        });
        jPanel1.add(bt_9);
        bt_9.setBounds(180, 180, 60, 50);

        bt_6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_6.setText("6");
        bt_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_6ActionPerformed(evt);
            }
        });
        jPanel1.add(bt_6);
        bt_6.setBounds(180, 240, 60, 50);

        bt_1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_1.setText("1");
        bt_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_1ActionPerformed(evt);
            }
        });
        jPanel1.add(bt_1);
        bt_1.setBounds(40, 300, 60, 50);

        bt_C.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bt_C.setText("C");
        bt_C.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 3));
        bt_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CActionPerformed(evt);
            }
        });
        jPanel1.add(bt_C);
        bt_C.setBounds(30, 360, 70, 60);

        bt_2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_2.setText("2");
        bt_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_2ActionPerformed(evt);
            }
        });
        jPanel1.add(bt_2);
        bt_2.setBounds(110, 300, 60, 50);

        bt_titik.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_titik.setText(".");
        bt_titik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_titikActionPerformed(evt);
            }
        });
        jPanel1.add(bt_titik);
        bt_titik.setBounds(180, 360, 60, 50);

        bt_3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_3.setText("3");
        bt_3.setMaximumSize(new java.awt.Dimension(100, 1));
        bt_3.setMinimumSize(new java.awt.Dimension(1, 31));
        bt_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_3ActionPerformed(evt);
            }
        });
        jPanel1.add(bt_3);
        bt_3.setBounds(180, 300, 60, 50);

        bt_hasil.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bt_hasil.setText("=");
        bt_hasil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 3));
        bt_hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hasilActionPerformed(evt);
            }
        });
        jPanel1.add(bt_hasil);
        bt_hasil.setBounds(30, 430, 110, 50);

        bt_tambah.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_tambah.setText("+");
        bt_tambah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153), 2));
        bt_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahActionPerformed(evt);
            }
        });
        jPanel1.add(bt_tambah);
        bt_tambah.setBounds(250, 180, 60, 40);

        bt_kurang.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_kurang.setText("-");
        bt_kurang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153), 2));
        bt_kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_kurangActionPerformed(evt);
            }
        });
        jPanel1.add(bt_kurang);
        bt_kurang.setBounds(250, 230, 60, 40);

        bt_kali.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_kali.setText("X");
        bt_kali.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153), 2));
        bt_kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_kaliActionPerformed(evt);
            }
        });
        jPanel1.add(bt_kali);
        bt_kali.setBounds(250, 280, 60, 40);

        bt_bagi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_bagi.setText("/");
        bt_bagi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153), 2));
        bt_bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_bagiActionPerformed(evt);
            }
        });
        jPanel1.add(bt_bagi);
        bt_bagi.setBounds(250, 330, 60, 40);

        bt_mod.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_mod.setText("mod");
        bt_mod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153), 2));
        bt_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modActionPerformed(evt);
            }
        });
        jPanel1.add(bt_mod);
        bt_mod.setBounds(150, 430, 160, 40);

        bt_10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_10.setText("0");
        bt_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_10ActionPerformed(evt);
            }
        });
        jPanel1.add(bt_10);
        bt_10.setBounds(110, 360, 60, 50);

        bt_sisabagi1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_sisabagi1.setText("%");
        bt_sisabagi1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153), 2));
        bt_sisabagi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sisabagi1ActionPerformed(evt);
            }
        });
        jPanel1.add(bt_sisabagi1);
        bt_sisabagi1.setBounds(250, 380, 60, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 440, 510);
        jPanel1.getAccessibleContext().setAccessibleName("Kalkulator Sederhana");

        setSize(new java.awt.Dimension(367, 536));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_7ActionPerformed
        bil += "7";
        txt_hasil.setText(bil);
    }//GEN-LAST:event_bt_7ActionPerformed

    private void bt_titikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_titikActionPerformed
        bil += ".";
        txt_hasil.setText(bil);
    }//GEN-LAST:event_bt_titikActionPerformed

    private void bt_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_1ActionPerformed
        bil +="1";
        txt_hasil.setText(bil);
    }//GEN-LAST:event_bt_1ActionPerformed

    private void bt_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_2ActionPerformed
        bil += "2";
        txt_hasil.setText(bil);
    }//GEN-LAST:event_bt_2ActionPerformed

    private void bt_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_3ActionPerformed
        bil += "3";
        txt_hasil.setText(bil);
    }//GEN-LAST:event_bt_3ActionPerformed

    private void bt_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_4ActionPerformed
        bil += "4";
        txt_hasil.setText(bil);
    }//GEN-LAST:event_bt_4ActionPerformed

    private void bt_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_5ActionPerformed
        bil += "5";
        txt_hasil.setText(bil);
    }//GEN-LAST:event_bt_5ActionPerformed

    private void bt_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_6ActionPerformed
        bil += "6";
        txt_hasil.setText(bil);
    }//GEN-LAST:event_bt_6ActionPerformed

    private void bt_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_8ActionPerformed
        bil += "8";
        txt_hasil.setText(bil);
    }//GEN-LAST:event_bt_8ActionPerformed

    private void bt_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_9ActionPerformed
        bil += "9";
        txt_hasil.setText(bil);
    }//GEN-LAST:event_bt_9ActionPerformed

    private void bt_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CActionPerformed
        txt_hasil.setText(null);
        bil1=0.0;
        bil2=0.0;
        jumlah=0.0;
        bil="";
    }//GEN-LAST:event_bt_CActionPerformed

    private void bt_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahActionPerformed
        bil1 =Double.parseDouble(bil);
        txt_hasil.setText("+");
        bil="";
        pilih=1; 
    }//GEN-LAST:event_bt_tambahActionPerformed

    private void bt_kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_kurangActionPerformed
        bil1 =Double.parseDouble(bil);
        txt_hasil.setText("-");
        bil="";
        pilih=2;
    }//GEN-LAST:event_bt_kurangActionPerformed

    private void bt_kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_kaliActionPerformed
        bil1 =Double.parseDouble(bil);
        txt_hasil.setText("*");
        bil="";
        pilih=3;
    }//GEN-LAST:event_bt_kaliActionPerformed

    private void bt_bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_bagiActionPerformed
        bil1 =Double.parseDouble(bil);
        txt_hasil.setText("/");
        bil="";
        pilih=4;
    }//GEN-LAST:event_bt_bagiActionPerformed

    private void bt_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modActionPerformed
        bil1 =Double.parseDouble(bil);
        txt_hasil.setText("%");
        bil="";
        pilih=5;
    }//GEN-LAST:event_bt_modActionPerformed

    private void bt_hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hasilActionPerformed
        switch(pilih){
        case 1:
            bil2 = Double.parseDouble(String.valueOf(txt_hasil.getText()));
            jumlah = bil1+bil2;
            bil = Double.toString(jumlah);            
            break;
        case 2:
            bil2 =Double.parseDouble(String.valueOf(txt_hasil.getText()));
            jumlah = bil1 - bil2;
            bil = Double.toString(jumlah);            
            break;
        case 3:
            bil2 = Double.parseDouble(String.valueOf(txt_hasil.getText()));
            jumlah = bil1 * bil2;
            bil = Double.toString(jumlah);            
            break;
        case 4:
            bil2 = Double.parseDouble(String.valueOf(txt_hasil.getText()));
            jumlah = bil1 / bil2;
            bil = Double.toString(jumlah);            
            break;
        case 5:
            bil2 = Double.parseDouble(String.valueOf(txt_hasil.getText()));
            jumlah = bil1 % bil2;
            bil = Double.toString(jumlah);            
            break;
        case 6:
            bil2 = Double.parseDouble(String.valueOf(txt_hasil.getText()));
            jumlah = bil1/100;
            bil = Double.toString(jumlah);
            break;
        } 
        txt_hasil.setText(bil);
    }//GEN-LAST:event_bt_hasilActionPerformed

    private void bt_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_10ActionPerformed
        bil += "0";
        txt_hasil.setText(bil);
    }//GEN-LAST:event_bt_10ActionPerformed

    private void bt_sisabagi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sisabagi1ActionPerformed
        bil1 =Double.parseDouble(bil);
        txt_hasil.setText(bil);
        bil="";
        pilih=6;
    }//GEN-LAST:event_bt_sisabagi1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Standard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Standard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Standard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Standard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Standard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_1;
    private javax.swing.JButton bt_10;
    private javax.swing.JButton bt_2;
    private javax.swing.JButton bt_3;
    private javax.swing.JButton bt_4;
    private javax.swing.JButton bt_5;
    private javax.swing.JButton bt_6;
    private javax.swing.JButton bt_7;
    private javax.swing.JButton bt_8;
    private javax.swing.JButton bt_9;
    private javax.swing.JButton bt_C;
    private javax.swing.JButton bt_bagi;
    private javax.swing.JButton bt_hasil;
    private javax.swing.JButton bt_kali;
    private javax.swing.JButton bt_kurang;
    private javax.swing.JButton bt_mod;
    private javax.swing.JButton bt_sisabagi1;
    private javax.swing.JButton bt_tambah;
    private javax.swing.JButton bt_titik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txt_hasil;
    // End of variables declaration//GEN-END:variables
}
